import { supabase } from '../lib/supabaseClient';
import type {
  PartyLedger,
  CreateLedgerInput,
  UpdateLedgerInput,
  PartyBalance,
  LedgerFilters,
  LedgerSummary,
  PartyOption,
  PartyType,
} from '../types/ledger.types';

class LedgerService {
  /**
   * Get all ledger entries with filters
   */
  async getLedgerEntries(filters?: LedgerFilters): Promise<PartyLedger[]> {
    let query = supabase
      .from('party_ledger')
      .select(`
        *,
        branches:branch_id(name)
      `)
      .order('transaction_date', { ascending: false })
      .order('created_at', { ascending: false });

    if (filters?.party_type) {
      query = query.eq('party_type', filters.party_type);
    }

    if (filters?.party_id) {
      query = query.eq('party_id', filters.party_id);
    }

    if (filters?.transaction_type) {
      query = query.eq('transaction_type', filters.transaction_type);
    }

    if (filters?.status) {
      query = query.eq('status', filters.status);
    }

    if (filters?.branch_id) {
      query = query.eq('branch_id', filters.branch_id);
    }

    if (filters?.start_date) {
      query = query.gte('transaction_date', filters.start_date);
    }

    if (filters?.end_date) {
      query = query.lte('transaction_date', filters.end_date);
    }

    if (filters?.search) {
      query = query.or(`party_name.ilike.%${filters.search}%,description.ilike.%${filters.search}%,ledger_number.ilike.%${filters.search}%`);
    }

    const { data, error } = await query;

    if (error) throw error;
    return data || [];
  }

  /**
   * Get ledger entry by ID
   */
  async getLedgerById(id: string): Promise<PartyLedger | null> {
    const { data, error } = await supabase
      .from('party_ledger')
      .select(`
        *,
        branches:branch_id(name)
      `)
      .eq('id', id)
      .single();

    if (error) throw error;
    return data;
  }

  /**
   * Get ledger entries for a specific party
   */
  async getPartyLedger(partyType: PartyType, partyId: string): Promise<PartyLedger[]> {
    const { data, error } = await supabase
      .from('party_ledger')
      .select(`
        *,
        branches:branch_id(name)
      `)
      .eq('party_type', partyType)
      .eq('party_id', partyId)
      .order('transaction_date', { ascending: false })
      .order('created_at', { ascending: false });

    if (error) throw error;
    return data || [];
  }

  /**
   * Create a new ledger entry
   */
  async createLedgerEntry(input: CreateLedgerInput): Promise<PartyLedger> {
    const { data: { user } } = await supabase.auth.getUser();
    
    // Get user name
    let createdByName = 'Unknown';
    if (user?.id) {
      const { data: userData } = await supabase
        .from('users')
        .select('name')
        .eq('id', user.id)
        .single();
      createdByName = userData?.name || 'Unknown';
    }

    const { data, error } = await supabase
      .from('party_ledger')
      .insert({
        ...input,
        ledger_number: '', // Will be generated by trigger
        status: 'completed',
        created_by: user?.id,
        created_by_name: createdByName,
      })
      .select()
      .single();

    if (error) throw error;
    return data;
  }

  /**
   * Update a ledger entry
   */
  async updateLedgerEntry(id: string, input: UpdateLedgerInput): Promise<PartyLedger> {
    const { data, error } = await supabase
      .from('party_ledger')
      .update({
        ...input,
        updated_at: new Date().toISOString(),
      })
      .eq('id', id)
      .select()
      .single();

    if (error) throw error;
    return data;
  }

  /**
   * Cancel a ledger entry
   */
  async cancelLedgerEntry(id: string): Promise<void> {
    const { error } = await supabase
      .from('party_ledger')
      .update({
        status: 'cancelled',
        updated_at: new Date().toISOString(),
      })
      .eq('id', id);

    if (error) throw error;
  }

  /**
   * Get party balances
   */
  async getPartyBalances(partyType?: PartyType): Promise<PartyBalance[]> {
    let query = supabase
      .from('vw_party_balance')
      .select('*')
      .order('party_name');

    if (partyType) {
      query = query.eq('party_type', partyType);
    }

    const { data, error } = await query;

    if (error) throw error;
    return data || [];
  }

  /**
   * Get balance for a specific party
   */
  async getPartyBalance(partyType: PartyType, partyId: string): Promise<PartyBalance | null> {
    const { data, error } = await supabase
      .from('vw_party_balance')
      .select('*')
      .eq('party_type', partyType)
      .eq('party_id', partyId)
      .single();

    if (error && error.code !== 'PGRST116') throw error;
    return data;
  }

  /**
   * Get ledger summary
   */
  async getLedgerSummary(filters?: LedgerFilters): Promise<LedgerSummary> {
    let query = supabase
      .from('party_ledger')
      .select('transaction_type, amount, status');

    if (filters?.party_type) {
      query = query.eq('party_type', filters.party_type);
    }

    if (filters?.party_id) {
      query = query.eq('party_id', filters.party_id);
    }

    if (filters?.branch_id) {
      query = query.eq('branch_id', filters.branch_id);
    }

    if (filters?.start_date) {
      query = query.gte('transaction_date', filters.start_date);
    }

    if (filters?.end_date) {
      query = query.lte('transaction_date', filters.end_date);
    }

    const { data, error } = await query;

    if (error) throw error;

    const entries = data || [];
    const completedEntries = entries.filter(e => e.status === 'completed');

    return {
      total_debit: completedEntries.filter(e => e.transaction_type === 'debit').reduce((sum, e) => sum + Number(e.amount), 0),
      total_credit: completedEntries.filter(e => e.transaction_type === 'credit').reduce((sum, e) => sum + Number(e.amount), 0),
      net_balance: completedEntries.reduce((sum, e) => sum + (e.transaction_type === 'debit' ? Number(e.amount) : -Number(e.amount)), 0),
      transaction_count: completedEntries.length,
      pending_count: entries.filter(e => e.status === 'pending').length,
    };
  }

  /**
   * Get all users as party options
   */
  async getUsers(): Promise<PartyOption[]> {
    const { data, error } = await supabase
      .from('users')
      .select('id, name, phone, email, employee_id')
      .eq('is_active', true)
      .order('name');

    if (error) throw error;

    return (data || []).map(user => ({
      id: user.id,
      name: user.name,
      type: 'user' as PartyType,
      code: user.employee_id || undefined,
      phone: user.phone || undefined,
      email: user.email || undefined,
    }));
  }

  /**
   * Get all installation teams as party options
   */
  async getInstallationTeams(): Promise<PartyOption[]> {
    const { data, error } = await supabase
      .from('installation_teams')
      .select('id, team_name, team_leader_contact, email')
      .eq('is_active', true)
      .order('team_name');

    if (error) throw error;

    return (data || []).map(team => ({
      id: team.id,
      name: team.team_name,
      type: 'installation_team' as PartyType,
      phone: team.team_leader_contact || undefined,
      email: team.email || undefined,
    }));
  }

  /**
   * Get all distributors as party options
   */
  async getDistributors(): Promise<PartyOption[]> {
    const { data, error } = await supabase
      .from('distributors')
      .select('id, company_name, distributor_code, phone, email')
      .eq('is_active', true)
      .order('company_name');

    if (error) throw error;

    return (data || []).map(dist => ({
      id: dist.id,
      name: dist.company_name,
      type: 'distributor' as PartyType,
      code: dist.distributor_code || undefined,
      phone: dist.phone || undefined,
      email: dist.email || undefined,
    }));
  }

  /**
   * Get all vendors as party options
   */
  async getVendors(): Promise<PartyOption[]> {
    const { data, error } = await supabase
      .from('vendors')
      .select('id, company_name, vendor_code, phone, email')
      .eq('is_active', true)
      .order('company_name');

    if (error) throw error;

    return (data || []).map(vendor => ({
      id: vendor.id,
      name: vendor.company_name,
      type: 'vendor' as PartyType,
      code: vendor.vendor_code || undefined,
      phone: vendor.phone || undefined,
      email: vendor.email || undefined,
    }));
  }

  /**
   * Get all customers/leads as party options (from leads table used in solar operations)
   */
  async getCustomers(): Promise<PartyOption[]> {
    const { data, error } = await supabase
      .from('leads')
      .select('id, customer_name, mobile, email, status')
      .order('customer_name');

    if (error) throw error;

    return (data || []).map(lead => ({
      id: lead.id,
      name: lead.customer_name,
      type: 'customer' as PartyType,
      phone: lead.mobile || undefined,
      email: lead.email || undefined,
    }));
  }

  /**
   * Get all parties of a specific type
   */
  async getParties(partyType: PartyType): Promise<PartyOption[]> {
    switch (partyType) {
      case 'user':
        return this.getUsers();
      case 'installation_team':
        return this.getInstallationTeams();
      case 'distributor':
        return this.getDistributors();
      case 'vendor':
        return this.getVendors();
      case 'customer':
        return this.getCustomers();
      default:
        return [];
    }
  }

  /**
   * Get all parties across all types
   */
  async getAllParties(): Promise<PartyOption[]> {
    const [users, teams, distributors, vendors, customers] = await Promise.all([
      this.getUsers(),
      this.getInstallationTeams(),
      this.getDistributors(),
      this.getVendors(),
      this.getCustomers(),
    ]);

    return [...users, ...teams, ...distributors, ...vendors, ...customers];
  }
}

export const ledgerService = new LedgerService();
export default ledgerService;
